(() => {
  "use strict";

  // CSS reference sizes, not physical panel pixels. See DEVICE-SOURCES.md for
  // provenance and the explicit scaling assumptions for desktop and Android.
  const rows = [
    [
      "iphone-17",
      "phone",
      "Apple",
      "iPhone 17 / 17 Pro",
      402,
      874,
      false,
      "6.3″ · 3× Retina",
    ],
    [
      "iphone-17-max",
      "phone",
      "Apple",
      "iPhone 17 Pro Max",
      440,
      956,
      false,
      "6.9″ · 3× Retina",
    ],
    [
      "iphone-air",
      "phone",
      "Apple",
      "iPhone Air",
      420,
      912,
      false,
      "6.5″ · 3× Retina",
    ],
    [
      "iphone-16",
      "phone",
      "Apple",
      "iPhone 16",
      393,
      852,
      false,
      "6.1″ · 3× Retina",
    ],
    [
      "galaxy-s26",
      "phone",
      "Samsung",
      "Galaxy S26",
      360,
      780,
      false,
      "6.3″ · reference at 3×",
    ],
    [
      "galaxy-s26-plus",
      "phone",
      "Samsung",
      "Galaxy S26+ / Ultra",
      412,
      892,
      false,
      "QHD+ · reference at 3.5×",
    ],
    [
      "iphone-se",
      "phone",
      "Apple",
      "iPhone SE",
      375,
      667,
      true,
      "Compact · 2nd / 3rd generation",
    ],
    [
      "iphone-5",
      "phone",
      "Apple",
      "iPhone 5 / SE (1st gen)",
      320,
      568,
      true,
      "Small-screen baseline",
    ],
    [
      "iphone-xr",
      "phone",
      "Apple",
      "iPhone XR",
      414,
      896,
      true,
      "6.1″ · 2× Retina",
    ],
    [
      "galaxy-s8",
      "phone",
      "Samsung",
      "Galaxy S8+",
      360,
      740,
      true,
      "Narrow Android baseline",
    ],
    [
      "galaxy-s20",
      "phone",
      "Samsung",
      "Galaxy S20 Ultra",
      412,
      915,
      true,
      "6.9″ · DevTools reference",
    ],
    [
      "ipad-pro-11",
      "tablet",
      "Apple",
      "iPad Pro 11″",
      834,
      1210,
      false,
      "M5 · 2× Retina",
    ],
    [
      "ipad-pro-13",
      "tablet",
      "Apple",
      "iPad Pro 13″",
      1032,
      1376,
      false,
      "M5 · 2× Retina",
    ],
    [
      "ipad-mini",
      "tablet",
      "Apple",
      "iPad mini",
      744,
      1133,
      false,
      "A17 Pro · 8.3″",
    ],
    [
      "galaxy-tab-s11",
      "tablet",
      "Samsung",
      "Galaxy Tab S11",
      800,
      1280,
      false,
      "11″ · reference at 2×",
    ],
    [
      "galaxy-tab-s11-ultra",
      "tablet",
      "Samsung",
      "Galaxy Tab S11 Ultra",
      924,
      1480,
      false,
      "14.6″ · reference at 2×",
    ],
    [
      "ipad-classic",
      "tablet",
      "Apple",
      "iPad / iPad mini (classic)",
      768,
      1024,
      true,
      "Classic 4:3 baseline",
    ],
    [
      "galaxy-tab-s4",
      "tablet",
      "Samsung",
      "Galaxy Tab S4",
      712,
      1138,
      true,
      "10.5″ · DevTools reference",
    ],
    [
      "macbook-air-13",
      "laptop",
      "Apple",
      "MacBook Air 13″",
      1280,
      832,
      false,
      "M5 · reference at 2×",
    ],
    [
      "macbook-air-15",
      "laptop",
      "Apple",
      "MacBook Air 15″",
      1440,
      932,
      false,
      "M5 · reference at 2×",
    ],
    [
      "macbook-pro-14",
      "laptop",
      "Apple",
      "MacBook Pro 14″",
      1512,
      982,
      false,
      "Retina · reference at 2×",
    ],
    [
      "macbook-pro-16",
      "laptop",
      "Apple",
      "MacBook Pro 16″",
      1728,
      1117,
      false,
      "Retina · reference at 2×",
    ],
    [
      "galaxy-book6-14",
      "laptop",
      "Samsung",
      "Galaxy Book6 Pro 14″",
      1440,
      900,
      false,
      "2880 × 1800 · 200% scaling",
    ],
    [
      "galaxy-book6-16",
      "laptop",
      "Samsung",
      "Galaxy Book6 Pro 16″",
      1920,
      1200,
      false,
      "2880 × 1800 · 150% scaling",
    ],
    [
      "macbook-air-legacy",
      "laptop",
      "Apple",
      "MacBook Air 13″ (Intel)",
      1440,
      900,
      true,
      "Non-Retina · 2017",
    ],
    [
      "samsung-series-9",
      "laptop",
      "Samsung",
      "Series 9 13″",
      1600,
      900,
      true,
      "2012 · HD+ at 100% scaling",
    ],
    [
      "monitor-24-fhd",
      "monitor",
      "Standard",
      "24″ Full HD",
      1920,
      1080,
      false,
      "1080p · 100% scaling",
    ],
    [
      "monitor-24-qhd",
      "monitor",
      "Standard",
      "24″ QHD",
      2048,
      1152,
      false,
      "1440p · 125% scaling",
    ],
    [
      "monitor-27-qhd",
      "monitor",
      "Standard",
      "27″ QHD",
      2560,
      1440,
      false,
      "1440p · 100% scaling",
    ],
    [
      "monitor-27-4k",
      "monitor",
      "Standard",
      "27″ 4K",
      1920,
      1080,
      false,
      "2160p · 200% scaling",
    ],
    [
      "studio-display",
      "monitor",
      "Apple",
      "Studio Display 27″",
      2560,
      1440,
      false,
      "5K · reference at 2×",
    ],
    [
      "monitor-32-4k",
      "monitor",
      "Standard",
      "32″ 4K",
      2560,
      1440,
      false,
      "2160p · 150% scaling",
    ],
    [
      "monitor-32-native",
      "monitor",
      "Standard",
      "32″ 4K · native",
      3840,
      2160,
      false,
      "2160p · 100% scaling",
    ],
    [
      "monitor-24-legacy",
      "monitor",
      "Standard",
      "24″ WUXGA",
      1920,
      1200,
      true,
      "Classic 16:10 · 100% scaling",
    ],
  ];
  const devices = Object.freeze(
    rows.map(([id, type, brand, name, width, height, legacy, detail]) =>
      Object.freeze({ id, type, brand, name, width, height, legacy, detail }),
    ),
  );
  const types = Object.freeze(["phone", "tablet", "laptop", "monitor"]);

  function dimensions(device, rotated = false) {
    return rotated && (device.type === "phone" || device.type === "tablet")
      ? { width: device.height, height: device.width }
      : { width: device.width, height: device.height };
  }

  function filter({
    type,
    maxWidth,
    query = "",
    legacyOnly = false,
    rotated = false,
  }) {
    const terms = query.toLowerCase().trim().split(/\s+/);
    return devices.filter((device) => {
      const size = dimensions(device, rotated);
      const searchable =
        `${device.brand} ${device.name} ${device.detail} ${size.width} ${size.height} ${device.legacy ? "legacy" : ""}`.toLowerCase();
      return (
        device.type === type &&
        size.width <= maxWidth &&
        (!legacyOnly || device.legacy) &&
        terms.every((term) => searchable.includes(term))
      );
    });
  }

  globalThis.viewportDevicePresets = Object.freeze({
    devices,
    types,
    dimensions,
    filter,
  });
})();
